name: Build ImmortalWrt (WR30U mt7981)

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      # ✅ 释放空间
      - name: Maximize disk space
        uses: easimon/maximize-build-space@v10
        with:
          root-reserve-mb: 512
          swap-size-mb: 4096
          remove-dotnet: true
          remove-android: true
          remove-haskell: true

      - name: Clean environment
        run: |
          sudo apt-get clean
          docker image prune -a -f || true
          df -h

      # ✅ 安装依赖
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential clang flex bison g++ gawk gcc-multilib gettext git \
            libncurses5-dev libssl-dev python3 python3-distutils python3-setuptools \
            rsync unzip zlib1g-dev file wget time ccache

      # ✅ 克隆 ImmortalWrt 源码（指定分支）
      - name: Clone ImmortalWrt
        run: |
          git clone https://github.com/immortalwrt/immortalwrt.git -b master
          cd immortalwrt
          echo "Cloned ImmortalWrt source tree:"
          git log -1

      # ✅ 添加额外软件包（主题、ddns-go、openclash）
      - name: Add extra packages
        run: |
          cd immortalwrt/package
          mkdir -p custom
          cd custom
          
          # 主题
          git clone --depth=1 https://github.com/sbwml/luci-theme-argon.git luci-theme-argon
          git clone --depth=1 https://github.com/sbwml/luci-app-argon-config.git luci-app-argon-config

          # DDNS-Go
          git clone --depth=1 https://github.com/sirpdboy/luci-app-ddns-go.git

          # OpenClash
          git clone --depth=1 https://github.com/vernesong/OpenClash.git luci-app-openclash

          # 其他可选插件可在这里继续添加

      # ✅ 更新 feeds
      - name: Update and install feeds
        run: |
          cd immortalwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      # ✅ 设备配置（Mi Router WR30U / MT7981）
      - name: Generate config
        run: |
          cd immortalwrt
          rm -f .config
          make menuconfig # ← 你可手动生成后保存为 config.seed 并替换掉
          # 如果要自动化，可以用 echo 指定
          # echo "CONFIG_TARGET_mediatek=y" >> .config
          # echo "CONFIG_TARGET_mediatek_filogic=y" >> .config
          # echo "CONFIG_TARGET_mediatek_filogic_DEVICE_xiaomi_wr30u=y" >> .config
          # echo "CONFIG_PACKAGE_luci-app-openclash=y" >> .config
          # echo "CONFIG_PACKAGE_luci-app-ddns-go=y" >> .config
          # echo "CONFIG_PACKAGE_luci-theme-argon=y" >> .config
          # echo "CONFIG_PACKAGE_luci-app-argon-config=y" >> .config
          # echo "CONFIG_DEVEL=y" >> .config
          # echo "CONFIG_CCACHE=y" >> .config
          # make defconfig
          cat .config

      # ✅ 下载源码包
      - name: Download sources
        run: |
          cd immortalwrt
          make download -j$(nproc)

      # ✅ 编译
      - name: Build firmware
        run: |
          cd immortalwrt
          make -j$(nproc) || make -j1 V=s

      # ✅ 整理与上传
      - name: Organize firmware
        run: |
          cd immortalwrt
          mkdir -p ../output
          find bin/targets/ -type f \( -name "*.bin" -o -name "*.img" -o -name "*.gz" \) -exec cp {} ../output/ \;
          df -h
          ls -lh ../output

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: immortalwrt-wr30u
          path: output
