name: Build ImmortalWRT for WR30U

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      TZ: Asia/Shanghai
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
            gettext git libncurses5-dev libssl-dev python3-distutils rsync unzip zlib1g-dev file wget

      - name: Clone ImmortalWRT source
        run: |
          git clone https://github.com/hanwckf/immortalwrt-mt798x.git immortalwrt
          cd immortalwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          # 添加额外包
          git clone https://github.com/jerrykuku/luci-theme-argon.git package/luci-theme-argon
          git clone https://github.com/vernesong/OpenClash.git package/luci-app-openclash
          git clone https://github.com/sirpdboy/luci-app-ddns-go.git package/luci-app-ddns-go
          # 生成默认配置
          make defconfig

      - name: Configure target
        working-directory: immortalwrt
        run: |
          # 自动写入 target 配置
          sed -i 's/CONFIG_TARGET_.*=.*/#&/' .config
          echo "CONFIG_TARGET_mediatek=y" >> .config
          echo "CONFIG_TARGET_mediatek_filogic=y" >> .config
          echo "CONFIG_TARGET_mediatek_filogic_DEVICE_xiaomi_mi-router-wr30u=y" >> .config
          echo "CONFIG_PACKAGE_luci=y" >> .config
          echo "CONFIG_PACKAGE_luci-theme-argon=y" >> .config
          echo "CONFIG_PACKAGE_luci-app-openclash=y" >> .config
          echo "CONFIG_PACKAGE_luci-app-ddns-go=y" >> .config
          make defconfig

      - name: Build firmware
        working-directory: immortalwrt
        run: make -j$(nproc) V=s

      - name: Upload firmware to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: immortalwrt-wr30u
          path: immortalwrt/bin/targets/
