name: Build ImmortalWrt WR30U (MT7981)

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare build environment
        run: |
          sudo apt update
          sudo apt install -y build-essential clang flex bison g++ gawk gcc-multilib \
            g++-multilib gettext git libncurses5-dev libssl-dev python3-distutils \
            rsync unzip zlib1g-dev file wget curl
          sudo apt clean

      - name: Clone ImmortalWrt source
        run: |
          git clone https://github.com/immortalwrt/immortalwrt.git source
          cd source
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Add extra packages (themes & plugins)
        run: |
          mkdir -p source/package/custom
          cd source/package/custom
          
          # Argon Theme
          git clone --depth=1 https://github.com/jerrykuku/luci-theme-argon.git
          git clone --depth=1 https://github.com/jerrykuku/luci-app-argon-config.git
          
          # DDNS-Go
          git clone --depth=1 https://github.com/sirpdboy/luci-app-ddns-go.git
          
          # OpenClash
          git clone --depth=1 https://github.com/vernesong/OpenClash.git luci-app-openclash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure target device
        run: |
          cd source
          if [ -f ../.config ]; then
            echo "Using custom .config from repository root"
            cp ../.config .config
          else
            echo "No .config found, using default for mt7981 (Mi Router WR30U)"
            # 默认配置 MT7981 机型
            cat >> .config <<EOF
CONFIG_TARGET_mediatek=y
CONFIG_TARGET_mediatek_filogic=y
CONFIG_TARGET_mediatek_filogic_DEVICE_xiaomi_mi-router-wr30u=y
CONFIG_PACKAGE_luci=y
CONFIG_PACKAGE_luci-theme-argon=y
CONFIG_PACKAGE_luci-app-argon-config=y
CONFIG_PACKAGE_luci-app-ddns-go=y
CONFIG_PACKAGE_luci-app-openclash=y
EOF
          fi
          make defconfig

      - name: Enable build cache
        uses: actions/cache@v4
        with:
          path: |
            source/staging_dir
            source/build_dir
            source/dl
          key: immortalwrt-${{ hashFiles('source/feeds.conf.default') }}
          restore-keys: |
            immortalwrt-

      - name: Build firmware
        run: |
          cd source
          make -j$(nproc) || make -j1 V=s

      - name: Package firmware
        run: |
          mkdir -p output
          cp -rf source/bin/targets/*/*/*.bin output/ || true
          cp -rf source/bin/targets/*/*/*.img output/ || true
          cp -rf source/bin/packages output/ || true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: immortalwrt-wr30u
          path: output/

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: output/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
