name: Build ImmortalWrt

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup dependencies
        run: |
          sudo apt update
          sudo apt install -y git-core build-essential libncurses5-dev \
            zlib1g-dev gawk gettext libssl-dev xsltproc rsync wget unzip python3

      - name: Clone ImmortalWrt source
        run: |
          git clone --depth=1 https://github.com/immortalwrt/immortalwrt.git
          cd immortalwrt

      - name: Add custom packages
        working-directory: ./immortalwrt/package
        run: |
          mkdir -p custom
          cd custom
          # luci-theme-argon
          git clone --depth=1 https://github.com/jerrykuku/luci-theme-argon.git
          # luci-app-argon-config
          git clone --depth=1 https://github.com/jerrykuku/luci-app-argon-config.git
          # luci-app-ddns-go
          git clone --depth=1 https://github.com/sirpdboy/luci-app-ddns-go.git
          # luci-app-openclash
          git clone --depth=1 https://github.com/vernesong/OpenClash.git luci-app-openclash

      - name: Update and install feeds
        working-d
